model_name: roberta-base
batch_size: 64
max_len: 256
epochs: 50
lr: 5.0e-5
weight_decay: 0.01
warmup_ratio: 0.1
grad_accum_steps: 1
early_stopping_patience: 10
seed: 42
num_workers: 2
fp16: true
da: del
alpha_aug: 0.8
summarize: false
dk: null
spacy_model: en_core_web_sm
fields: title,brand,description,price,priceCurrency
max_field_len: 350
