#!/usr/bin/env python3
"""R10-C: (re)build the baseline SM gold from the K8 ground-truth mapping.

The baseline SM committee scores against
``usecases/<domain>/input/schemamatching/sm_mapping_gold.csv``. Before
R10-C this gold listed only the original handful of attributes, while the
variant ``sm_mapping.csv`` (generated by :mod:`apply_knob_08_naming` from
``config/knob_08_naming/<domain>.yaml``'s ``sm_mapping`` block) covers the
full per-domain schema. The mismatched ``n_columns`` made the
baseline-vs-variant SM macro_f1 delta meaningless.

This script regenerates the baseline gold from the *same* ``sm_mapping``
block the variant is generated from — using the original (un-renamed)
source column names — so the two sides score on an identical attribute
set + target mapping (apples-to-apples).
"""

from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from usecases_synthetic.lib.domain_config import (  # noqa: E402
    VALID_DOMAINS,
    load_knob_config,
)
from usecases_synthetic.lib.variant_loader import variant_root  # noqa: E402

logger = logging.getLogger(__name__)

_COLUMNS = [
    "source_dataset",
    "source_column",
    "target_dataset",
    "target_column",
    "score",
]


def build_sm_mapping_gold(domain: str) -> pd.DataFrame:
    """Build the full-scope baseline SM gold DataFrame for ``domain``.

    One row per ``(source, source_column -> target_column)`` in the K8
    ``sm_mapping`` ground truth, with the *original* source column names
    (the block's keys) and ``score = 1.0``.
    """
    cfg = load_knob_config(8, domain)
    sm_ground_truth: dict[str, dict[str, str]] = cfg.get("sm_mapping", {})
    if not sm_ground_truth:
        raise ValueError(f"knob 08 config for {domain!r} has no 'sm_mapping' block")
    rows: list[dict[str, object]] = []
    for source, mapping in sm_ground_truth.items():
        for source_col, target_col in mapping.items():
            rows.append(
                {
                    "source_dataset": source,
                    "source_column": source_col,
                    "target_dataset": domain,
                    "target_column": target_col,
                    "score": 1.0,
                }
            )
    return pd.DataFrame(rows, columns=_COLUMNS)


def gold_path(domain: str) -> Path:
    """Return the baseline ``sm_mapping_gold.csv`` path for ``domain``."""
    return (
        variant_root(domain, "baseline")
        / "input"
        / "schemamatching"
        / "sm_mapping_gold.csv"
    )


def write_sm_mapping_gold(domain: str, *, dest: Path | None = None) -> Path:
    """Write the refreshed SM gold for ``domain`` and return the path."""
    df = build_sm_mapping_gold(domain)
    out = dest or gold_path(domain)
    out.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(out, index=False)
    logger.info("Wrote %d SM-gold rows -> %s", len(df), out)
    return out


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Regenerate the baseline SM gold from the K8 sm_mapping block."
    )
    parser.add_argument(
        "--domain",
        action="append",
        help="Domain (repeatable). Omit to refresh all real domains.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print the row count + a diff against the existing gold; do not write.",
    )
    args = parser.parse_args()

    logging.basicConfig(
        level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s"
    )
    domains = args.domain or [
        d for d in sorted(VALID_DOMAINS) if not d.endswith("-small") and d != "movies"
    ]
    for domain in domains:
        df = build_sm_mapping_gold(domain)
        out = gold_path(domain)
        existing = len(pd.read_csv(out)) if out.exists() else 0
        if args.dry_run:
            logger.info(
                "%s: would write %d rows (was %d) -> %s",
                domain,
                len(df),
                existing,
                out,
            )
        else:
            write_sm_mapping_gold(domain)
            logger.info("%s: %d rows (was %d)", domain, len(df), existing)


if __name__ == "__main__":
    main()
